### ISSUE TITLE
Show comments on comments you've made

### ISSUE THREAD

**Issue by joakimk** [henrik/remit#51]
I've looked a bit at this. It seems like we could show comments where the **sha1**, **position** and **line** is the same as a comment that is shown.

**Comment by henrik** [comment]
Seems reasonable!

**Comment by henrik** [comment]
Maybe an elegant way to code this then would be store something like comments.thread_identifier = "#{sha1}-#{position}-#{line}" on each comment and just use that later.

**Comment by joakimk** [comment]
Implemented this feature. Didn't write any tests since it seems we haven't done so before for similar things in this app.
